#!/usr/bin/env node
/**
 * Removes generated native projects and their build caches, so the next
 * prebuild starts from nothing.
 *
 *   npm run clean                # ios + android
 *   npm run clean:ios
 *   npm run clean:android
 *   npm run clean -- --dry-run   # list what would go, delete nothing
 *
 * ios/ and android/ are generated by `expo prebuild` and are gitignored, so
 * nothing here is a source file. `expo prebuild --clean` regenerates them but
 * leaves Xcode's DerivedData and Metro's cache in place -- which is exactly
 * where a stale build hides after an SDK upgrade.
 *
 * DerivedData lives outside the project, so directories are matched by reading
 * each one's info.plist and comparing its WorkspacePath against this project,
 * rather than by guessing at a name.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CLIENT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
const DERIVED_DATA_ROOT = join(homedir(), "Library", "Developer", "Xcode", "DerivedData");

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const platform = args.find((a) => !a.startsWith("--")) ?? "all";

if (!["ios", "android", "all"].includes(platform)) {
  console.error(`clean-native: unknown platform "${platform}". Use ios, android or all.`);
  process.exit(1);
}

/** Best effort; `du` on a large tree is slow but this runs rarely. */
const sizeOf = (path) => {
  try {
    return execFileSync("du", ["-sh", path], { encoding: "utf8" }).split("\t")[0].trim();
  } catch {
    return "?";
  }
};

/**
 * DerivedData directories belonging to this project.
 *
 * Xcode names them <Scheme>-<hash> and the hash changes, so the only reliable
 * test is the WorkspacePath recorded inside.
 */
const derivedDataForProject = () => {
  if (!existsSync(DERIVED_DATA_ROOT)) return [];

  return readdirSync(DERIVED_DATA_ROOT)
    .map((name) => join(DERIVED_DATA_ROOT, name))
    .filter((dir) => {
      const plist = join(dir, "info.plist");
      if (!existsSync(plist)) return false;
      try {
        const workspace = execFileSync(
          "/usr/libexec/PlistBuddy",
          ["-c", "Print :WorkspacePath", plist],
          { encoding: "utf8" },
        ).trim();
        return workspace.startsWith(CLIENT_DIR);
      } catch {
        // No WorkspacePath, or an unreadable plist: not ours to delete.
        return false;
      }
    });
};

/** Metro keeps caches in the system temp dir, keyed by a hash we cannot predict. */
const metroCaches = () => {
  try {
    return readdirSync(tmpdir())
      .filter((name) => name.startsWith("metro-") || name.startsWith("haste-map-"))
      .map((name) => join(tmpdir(), name));
  } catch {
    return [];
  }
};

const targets = [];

if (platform === "ios" || platform === "all") {
  targets.push(
    { label: "ios (generated project + Pods)", path: join(CLIENT_DIR, "ios") },
    ...derivedDataForProject().map((path) => ({ label: "Xcode DerivedData", path })),
  );
}

if (platform === "android" || platform === "all") {
  targets.push({
    label: "android (generated project + Gradle output)",
    path: join(CLIENT_DIR, "android"),
  });
}

// Shared caches. A stale Metro cache survives a native clean and will happily
// serve the previous bundle.
targets.push(
  { label: "Expo cache", path: join(CLIENT_DIR, ".expo") },
  { label: "Metro/node cache", path: join(CLIENT_DIR, "node_modules", ".cache") },
  ...metroCaches().map((path) => ({ label: "Metro temp cache", path })),
);

const present = targets.filter(
  (target, index) =>
    existsSync(target.path) &&
    // Drop anything nested inside another target, and any duplicate path.
    !targets.some((other) => target.path.startsWith(`${other.path}/`)) &&
    targets.findIndex((other) => other.path === target.path) === index,
);

if (present.length === 0) {
  console.log(`clean-native (${platform}): nothing to remove — already clean.`);
  process.exit(0);
}

console.log(`clean-native (${platform})${dryRun ? " — DRY RUN, nothing deleted" : ""}\n`);

for (const { label, path } of present) {
  console.log(`  ${dryRun ? "would remove" : "removing"}  ${sizeOf(path).padStart(6)}  ${label}`);
  console.log(`              ${path}`);
  if (dryRun) continue;
  try {
    rmSync(path, { recursive: true, force: true });
  } catch (error) {
    console.error(`  failed: ${error.message}`);
    process.exitCode = 1;
  }
}

if (dryRun) {
  console.log("\nRe-run without --dry-run to delete.");
} else {
  const flag =
    platform === "all" ? "" : ` --platform ${platform}`;
  console.log(`\nDone. Regenerate with:\n  npx expo prebuild${flag} --clean`);
}
