/**
 * The Privacy Policy and Terms, as data. The app renders them at /privacy and
 * /terms (also served on throttlebase.in), and `npm run legal:drafts` writes
 * the same text to docs/legal/drafts/ for legal review, so the page and the
 * draft a lawyer reads can never drift apart.
 *
 * A document's `version` is what a rider accepts at sign-up. The server only
 * creates an account when it matches its TERMS_VERSION / PRIVACY_VERSION, so
 * bump both together whenever the text changes.
 */

export type LegalBlock =
  | { kind: "paragraph"; text: string }
  | { kind: "list"; items: readonly string[] };

export interface LegalSection {
  heading: string;
  blocks: readonly LegalBlock[];
}

export interface LegalDocument {
  title: string;
  /** Date-based, e.g. "2026-09-29"; recorded in rider_consents at sign-up. */
  version: string;
  /** "draft" until a lawyer has approved the text; pages then show a notice. */
  status: "draft" | "final";
  /** A short, plain-language summary shown above the full text. */
  summary: readonly string[];
  sections: readonly LegalSection[];
}

export const paragraph = (text: string): LegalBlock => ({ kind: "paragraph", text });

export const list = (...items: string[]): LegalBlock => ({ kind: "list", items });

/** Placeholders a human must fill in before the text is final, e.g. "[GRIEVANCE OFFICER NAME]". */
export const PLACEHOLDER = /\[[A-Z][A-Z0-9 ,/'-]+\]/g;

const textsOf = (document: LegalDocument): string[] => [
  ...document.summary,
  ...document.sections.flatMap((section) => [
    section.heading,
    ...section.blocks.flatMap((block) => (block.kind === "paragraph" ? [block.text] : [...block.items])),
  ]),
];

export const placeholdersIn = (document: LegalDocument): string[] =>
  [...new Set(textsOf(document).flatMap((text) => text.match(PLACEHOLDER) ?? []))].sort();

const DRAFT_BANNER = "> **DRAFT — NOT LEGAL ADVICE.** Generated from the app (`client/src/core/legal/`); do not edit this file by hand.";

/** The document as Markdown, for review outside the app. */
export const toMarkdown = (document: LegalDocument): string => {
  const lines: string[] = [`# ${document.title}`, "", `Version ${document.version}`, ""];
  if (document.status === "draft") lines.push(DRAFT_BANNER, "");

  lines.push("## In short", "", ...document.summary.map((point) => `- ${point}`), "");

  for (const section of document.sections) {
    lines.push(`## ${section.heading}`, "");
    for (const block of section.blocks) {
      if (block.kind === "paragraph") lines.push(block.text, "");
      else lines.push(...block.items.map((item) => `- ${item}`), "");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
};
