import React, { memo } from "react";
import { Marker } from "../../../components/MapWrapper";
import { useTracksViewChanges } from "../hooks/useTracksViewChanges";
import type { LatLng } from "../types/navigation";

// Generated by scripts/generate-nav-puck.mjs; Metro picks the @2x/@3x variant for the screen.
const PUCK_IMAGE = require("../../../../assets/navigation/rider-puck.png");
const CENTER_ANCHOR = { x: 0.5, y: 0.5 };
/** Above waypoints and peers: the rider must never lose sight of themselves. */
const PUCK_Z_INDEX = 100;

export interface RiderPuckProps {
  coordinate: LatLng;
  /** Direction of travel in degrees from north. */
  headingDegrees: number;
}

/**
 * The rider's own position: a chevron lying flat on the map. A flat marker's
 * rotation is measured from north on both platforms even when the camera is
 * heading-up, so passing the absolute course points it the way the rider is
 * moving. It is a bitmap rather than a child view because Android
 * re-snapshots child-view markers whenever they change.
 *
 * `tracksViewChanges` is briefly re-enabled on every position update rather
 * than left permanently false: with the polyline and other markers on this
 * map redrawing continuously while the rider moves, a marker the native map
 * SDK is never asked to re-track can silently drop out of the map after a
 * while (seen on the Google Maps iOS SDK). Same fix as `WaypointMarker`.
 */
export const RiderPuck = memo(function RiderPuck({ coordinate, headingDegrees }: RiderPuckProps) {
  const tracksViewChanges = useTracksViewChanges(
    `${coordinate.latitude.toFixed(6)},${coordinate.longitude.toFixed(6)}`,
  );

  return (
    <Marker
      coordinate={coordinate}
      image={PUCK_IMAGE}
      flat
      rotation={headingDegrees}
      anchor={CENTER_ANCHOR}
      zIndex={PUCK_Z_INDEX}
      tracksViewChanges={tracksViewChanges}
      title='You'
    />
  );
});
