import React, { memo } from "react";
import { Marker } from "../../../components/MapWrapper";
import type { LatLng } from "../types/navigation";

// Generated by scripts/generate-nav-puck.mjs; Metro picks the @2x/@3x variant for the screen.
const PUCK_IMAGE = require("../../../../assets/navigation/rider-puck.png");
const CENTER_ANCHOR = { x: 0.5, y: 0.5 };
/** Above waypoints and peers: the rider must never lose sight of themselves. */
const PUCK_Z_INDEX = 100;

export interface RiderPuckProps {
  coordinate: LatLng;
  /** Direction of travel in degrees from north. */
  headingDegrees: number;
}

/**
 * The rider's own position: a chevron lying flat on the map. A flat marker's
 * rotation is measured from north on both platforms even when the camera is
 * heading-up, so passing the absolute course points it the way the rider is
 * moving. It is a bitmap rather than a child view because Android
 * re-snapshots child-view markers whenever they change.
 */
export const RiderPuck = memo(function RiderPuck({ coordinate, headingDegrees }: RiderPuckProps) {
  return (
    <Marker
      coordinate={coordinate}
      image={PUCK_IMAGE}
      flat
      rotation={headingDegrees}
      anchor={CENTER_ANCHOR}
      zIndex={PUCK_Z_INDEX}
      tracksViewChanges={false}
      title='You'
    />
  );
});
